version: '3.9'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./catalog:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_DATABASE: shop
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    command: >
      sh -c "
        composer install &&
        php artisan key:generate &&
        php artisan migrate --force || true &&
        php-fpm
      "

  web:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./catalog:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: catalog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    volumes:
      - ./catalog/test.sql:/docker-entrypoint-initdb.d/test.sql
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
